base architecture
Orendev/gokeeper pull request #2
Opened 2023-09-21 16:10 UTC by Orendev

2023-09-29 15:16 UTC, bambruysk requested changes
Очень классно сделано.

Дальше осталось покрыте тестами!

2023-09-29 15:16 UTC, bambruysk commented on internal/app/client/domain/account/type.go
> +	"time"
импорты нре отсортированы по группам

2023-09-29 15:16 UTC, bambruysk commented on internal/app/server/repository/storage/postgres/converterAccount.go
> +	}
Я бы здесь пакет  multierr   использовал

2023-09-29 15:16 UTC, bambruysk commented on pkg/protobuff/proto/keeper.proto
> +  string password = 4;
зачем обратно передавать пароль? вдруг кто что-где как перехватит)  Мне кажется он не нужен, ведь клиенту он известен

2023-09-29 15:16 UTC, bambruysk commented on pkg/tools/converter/string.go
> +	} else {
еlse тут лишнее -  ведь мы же вернулись в if
if len(str) == 0 {
		return uuid.Nil
}
if value, err := uuid.Parse(str); err != nil {
	return uuid.Nil
} 
return value
		
Более гошный стиль

2023-09-29 17:13 UTC, Orendev commented on pkg/tools/converter/string.go
> +	} else {
поправил

2023-09-29 17:14 UTC, Orendev commented on pkg/protobuff/proto/keeper.proto
> +  string password = 4;
поправил

2023-09-30 07:50 UTC, Orendev commented on internal/app/client/domain/account/type.go
> +	"time"
поправил

2023-10-17 16:19 UTC, merged